version: 2.1
orbs:
    win: circleci/windows@2.2.0

jobs:
    run-unit-tests:
        executor: win/default     
    
        steps:
            - checkout
            - run: dotnet build Currency-calculator\Currency-calculator
            - run: dotnet test Currency-calculator --test-adapter-path:. --logger:xunit
            - store_test_results:
                path: Currency-calculator\Currency_calculator.Tests\TestResults

workflows:
    version: 2
    Calculator_Workflow:
        jobs:
            - run-unit-tests