version: 2.1
orbs:
    win: circleci/windows@2.2.0

jobs:
    run-docker-compose:
        executor: win/default     
    
        steps:
            - checkout
            - run: docker-compose build
            - run: docker-compose up
                
    run-unit-tests:
        executor: win/default     
    
        steps:
            - checkout
            - run: dotnet build Currency-calculator\Currency-calculator
            - run: dotnet test Currency-calculator --test-adapter-path:. --logger:xunit
            - store_test_results:
                path: Currency-calculator\Currency_calculator.Tests\TestResults
                
    stop-docker-compose:
        executor: win/default     
    
        steps:
            - checkout
            - run: docker-compose down

workflows:
    version: 2
    Calculator_Workflow:
        jobs:
            - run-docker-compose
            - run-unit-tests:
                requires:
                    - run-docker-compose
            - stop-docker-compose:
                requires:
                    - run-unit-tests